#!/bin/sh

# Lots of these can also be put under the bin/ folder in a project
# using `bundle binstub <gemname>`

alias b="bundle"
alias be="bundle exec"
alias brake="bundle exec rake"
alias bguard="bundle exec guard"
alias bc="bundle console"
alias br="bin/rails"
alias brc="bin/rails console"
alias brdc="bin/rails db"
alias brdms="bin/rails db:migrate:status"
alias brdm="bin/rails db:migrate"
alias brr="bin/rails runner"
alias brs="bin/rails s"
alias brspec='bundle exec rspec -f d -c --fail-fast --order=defined'
alias bcuke='bundle exec cucumber'
alias bpry='bundle exec pry'
alias brdrop='bin/rails db:drop'
alias brcreate='bin/rails db:create'
alias brmig='bin/rails db:migrate'
alias brsclo='bin/rails db:schema:load'
alias brseed='bin/rails db:seed'
alias brdtp='bin/rails db:test:prepare'
alias brt='bin/rails test --verbose --fail-fast --seed=1000 '
