#!/bin/sh

# Aliases for doing npm stuff
alias npms='npm start'
alias npmr='npm run'
ailas npmt='npm test'
alias npmi='npm install'
alias npmis='npm install --save'
alias npmid='npm install --save-dev'
alias npmig='npm install --global'

# Aliases for yarn
alias y=yarn
alias ya='yarn add'
alias yad='yarn add --dev'
alias yga='yarn global add'
alias yag='yarn global add'
