#!/bin/sh
# variables to use to connect to remote sites
TTCOM=tamaratemple@tamaratemple.com; export TTCOM
alias ttcom="ssh $TTCOM"

FLAIMNET=tamouse@flaim.net; export FLAIMNET
alias flaim="ssh $FLAIMNET"

FKNET=tamouse@funkykitty.net; export FKNET
alias fknet="ssh $FKNET"

TPTGO=tptgo@tptgo.us; export TPTGO
alias tptgo="ssh $TPTGO";

GANDIMOUSE=tamara@gandimouse; export GANDIMOUSE
alias gandimouse="ssh $GANDIMOUSE"

export DH=dh-tamouse@hack.dreamwidth.net
alias dhack="ssh $DH"
