#!/bin/sh

alias gaa='git add --all -v'
alias ci='git add --all -v && git commit -m '
alias gb='git branch'
alias gbls='git branch -av'
alias gcl="git clone"
alias gcm='git commit -m'
alias gco='git checkout'
alias co='git checkout'
alias gcob='git checkout -b'
alias gd='git diff'
alias gl='git log'
alias glg='git log --graph --pretty=format":%C(yellow)%h%Cblue%d%Creset %s %C(white) %an,%ar%Creset" --abbrev-commit --decorate'
alias glgh='git log --graph --pretty=format":%C(yellow)%h%Cblue%d%Creset %s %C(white) %an,%ar%Creset" --abbrev-commit --decorate | head'
alias glo='git log --oneline --decorate'
alias glog='git log'
alias gloh='git log --oneline --decorate | head'
alias gls='git ls-files'
alias gpl='git pull'
alias gploh='git pull origin HEAD'
alias gps='git push'
alias gpsoh='git push -u origin HEAD'
alias gpsfoh='git push -fu origin HEAD'
alias gpsfuoh='git push -fu origin HEAD'
alias pufu='git push -fu origin HEAD'
alias gr='git remote'
alias grls='git remote -v'
alias gs='git status'
alias gorg='git remote -v|grep origin|grep push|cut -f2|cut -d" " -f1""'

# the one command to do them all!
# Usage: gacp 'commit message to use'
gacp () {
    git add --all -v && git commit -m "$1" && git push -u origin HEAD
}

alias gyolo='git add --all && git commit -m $(date "+YOLO.%FT%T") && git push -fu origin HEAD'

grurl () {
    xx_remote=$1
    [ -z "$xx_remote" ] && xx_remote=origin
    git remote --verbose | grep "$1" | grep fetch | cut -f2 | cut -d' ' -f1
    unset xx_remote
}
