#!/bin/bash
## Vagrant aliases, cos lazy
alias vs="vagrant ssh"
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias vdn="vagrant halt"
alias vsusp="vagrant suspend"
alias vp='vagrant provision'
alias vstat="vagrant status"
alias vdest="vagrant destroy"
alias vb="vagrant box"
alias vbl="vagrant box list"

v () {
    vagrant "$@"
}
